### ISSUE TITLE
Possible EXPORT to Bank issue in Windows 11

### ISSUE THREAD

**Issue by Andy1966uk** [remy/vscode-nextbasic#50]
I have a 2.08 CSPECT image now running in VSCode, but on 1.11.0 onwards, of the extension, , when I EXPORT to BANK, the resultant bank file in only 1k in size and doesn't seem to work.
I have to reverted back to 1.10.0 for the export to work properly. I am on Windows 11.
The banks file just has the header in it..

On Next KS1 and KS2 hardware the txt2bas works in converting the banks as my bank files start :
#bankfile ProcsBank1.bnk      etc.

Removing the #bankfile from the ProcsBank1.txt, it then works in CSPECT environment. Maybe there is a way to ignore this line in CSPECT ?

**Comment by NealeTools** [comment]
Hi Andy, I tried this using the RunInCSpect option and it makes the .bnk fine (or appears to):
<img width="585" alt="image" src="https://github.com/remy/vscode-nextbasic/assets/19664927/51ee64f7-638c-4e61-aba7-c86f1f93ecfa">

**Comment by remy** [comment]
@Andy1966uk do you have a sample of code to replicate with?

If cspect was running 2.07 I would understand there would be problems (and I need to expose the settings to change the targeted OS), but (from what I understand), 2.08 can handle a 1k bank, instead of padded to 16k.

**Comment by Andy1966uk** [comment]
can you share the test code above and I'll check... I am on windows, and I notice you are all on MACs. 
If I remove or REM out the first line of each bank excluding #bankfile ProcsBank1.bnk then it works , however my understanding is the line #bankfile ProcsBank1.bnk is needed on HW to convert text2bas as a BANK

**Comment by Andy1966uk** [comment]
I can work around this.

**Comment by remy** [comment]
@Andy1966uk if you manage to pare down some code that you're seeing it happen, you can share it with me and I can find out what's going on.

The Mac/Windows doesn't really make any difference because the process is running in JavaScript and it's running in the same engine (VS Code uses Chromium's JavaScript engine) - so because of this, it should (will!) behave the same. 

Which is a long way of saying, what you're seeing is a legit bug - I just can't replicate because I don't have enough details.
