### ISSUE TITLE
Program have stopped running under latest tversion

### ISSUE THREAD

**Issue by Andy1966uk** [remy/vscode-nextbasic#8]
Hi Remy, Programs that ran ok last night, now don;t run. When executing I get the below listing in CSPECT 
10  .cd devel
20  CLS
30  LOAD "INDEX.BAS"
40  RUN

Not sure what's changed....

**Comment by remy** [comment]
God damnit - on it - gimme 5!

**Comment by remy** [comment]
Change has gone up - there will be an update in a few minutes - 1.3.7

Sorry, I forget that what's in git isn't the same as what goes up to the vscode marketplace (I had some local changes I was experimenting with).

Going to close this, but ping me if there's a problem once you're on 1.3.7

**Comment by remy** [comment]
Hmm, I've got something weird going on in my own game at the moment. Do let me know if you're still having problems - I'll get it fixed quickly if I can.

**Comment by Andy1966uk** [comment]
Do programs now require #Autorun ? they used to launch straight into SCPECT and run, with having to add Autostart ?

**Comment by Andy1966uk** [comment]
Also assets don;t seem to get pushed across from what i can see.....

**Comment by remy** [comment]
Internally the extension adds the autostart so that it does launch immediately, but I managed to land a bug that _put_ that into the code when hitting save. I've reverted it and it's live with 1.3.8 (yes, I managed to release some very buggy code!!!).

Can you re-test the assets? I just tried with a clean/new cspect image and all my assets went across and the game auto-started as I'd expect it to.
